### ISSUE TITLE
official source of tinyfiledialogs

### ISSUE THREAD

**Issue by vareille** [Doublezer0/TinyFileDialogsUE4#3]
Hi, I am the author of tinyfiledialogs

Could you please indicate clearly that this is not the official source for tinyfiledialogs and indicate where to find it.
http://tinyfiledialogs.sourceforge.net

thanks in advance

guillaume vareille

**Comment by Doublezer0** [comment]
> 

Absolutely.  Not sure why I hadn't done this earlier.  My bad.

**Comment by vareille** [comment]
thanks

**Comment by Doublezer0** [comment]
Done.  And thanks for the original code. It was pretty nice to work with.
